[package]
name = "wireshark"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = { workspace = true }
iggy = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
