[package]
name = "wireshark"
version = "0.1.0"
edition = "2021"

[dependencies]
iggy_common = { workspace = true }
bytes = { workspace = true }
server = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
